name: CI
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test-bump-version:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_BASE_URL: ${{ secrets.VITE_SUPABASE_BASE_URL }}
      VITE_SUPABASE_API_KEY: ${{ secrets.VITE_SUPABASE_API_KEY }}
      VITE_SUPABASE_DATA_URL: ${{ secrets.VITE_SUPABASE_DATA_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Run tests
        run: yarn test:unit

      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run playwright tests
        run: npx playwright test

      - name: Version bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          major-wording: "major,Major"
          minor-wording: "minor,Minor"
          patch-wording: "patch,bug,Patch,Bug"
          commit-message: "CI: bump version to {{version}}"
